#!/bin/bash
# homebrewupdate


export PATH=/usr/local/bin:$PATH
notifier=terminal-notifier

# Give the network a chance to connect
sleep 10

brew update > /dev/null 2>&1
outdated=`brew outdated | sort | tr '\n' ' '`

if [ ! -z "$outdated" ]; then
	$notifier \
		-group my.mac.homebrewnotify \
		-title "Homebrew Updates Available" \
		-message "$outdated" \
		-activate com.apple.Terminal > /dev/null 2>&1

    if [ ! -z $1 ]; then
      echo $(hostname) : "$outdated" | mail -s "Homebrew Updates Available" $1
    fi
fi
